version: "3.9"

services:
  # ======================
  # DATABASE SERVICE
  # ======================
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - vcube_network

  # ======================
  # BACKEND (APP SERVER)
  # ======================
  app_server:
    build: ./app_server
    container_name: app_server
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "5001:5001"
    env_file:
      - ./app_server/.env
    volumes:
      - ./app_server:/app
    networks:
      - vcube_network

  # ======================
  # FRONTEND (WEB SERVER)
  # ======================
  web_server:
    build: ./web_server
    container_name: web_server
    restart: always
    depends_on:
      - app_server
    ports:
      - "5000:5000"
    env_file:
      - ./web_server/.env
    volumes:
      - ./web_server:/app
    networks:
      - vcube_network

# ======================
# NETWORK
# ======================
networks:
  vcube_network:
    driver: bridge
